version: '3'

tasks:
  build:
    desc: Build production kernel image
    cmds:
      - docker build -t teamagentica-kernel:latest --target prod .

  connect:
    desc: Connect to kernel via tacli and generate a valid jwt token
    dir: ..
    cmds:
      - go run ./tacli connect http://api.teamagentica.localhost --email chris@teamagentica.localhost --password 'FL3t9.Uk:xA44xK'

  get_token:
    desc: Gets the token from the default profile (useful for agents)
    dir: ..
    cmds:
      - cat ~/.config/teamagentica/tacli.json | jq -r '.profiles[] | select(.name=="default") | .token'

  start:
    desc: Start kernel via tacli
    dir: ..
    cmds:
      - go run ./tacli core start

  stop:
    desc: Stop kernel via tacli
    dir: ..
    cmds:
      - go run ./tacli core stop

  restart:
    desc: Restart kernel via tacli
    dir: ..
    cmds:
      - go run ./tacli core restart

  logs:
    desc: Follow kernel container logs
    dir: ..
    cmds:
      - go run ./tacli core logs

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf ./build
