[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/dev/null
logfile_maxbytes=0

[program:portpilot]
command=portpilot --listen :8080 --default 8081
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:code-server]
command=code-server --auth none --bind-addr 0.0.0.0:8081 --disable-telemetry --extensions-dir %(ENV_EXTENSIONS_DIR)s %(ENV_DEFAULT_WORKSPACE)s
autorestart=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
